### ISSUE TITLE
http-problem isn't compatible with axum 0.6

### ISSUE THREAD

**Issue by dbofmmbt** [terramagna/http-problem#4]
The current version of `http-problem` only works with axum 0.5.  If you use it with axum 0.6, you get a compilation error as your handler function doesn't implement `IntoResponse`.

As axum is not stable yet, one alternative is to add feature flags for each unstable version and implement `IntoResponse` for the versions with feature flag on. I suppose this would avoid `http-problem` to have to increase its 0.X version every time axum upgrades.

**Comment by luisholanda** [comment]
Hi @dbofmmbt. @saiintbrisson is updating our internal monorepo to the latest `axum` version, which includes the work to update `http-problem`. As soon as this work is complete, we will release a new version in crates.io.
